### ISSUE TITLE
Change GaugeColor after viewDidLoad

### ISSUE THREAD

**Issue by lisardo** [BelkaLab/GaugeView#1]
Hi BelkaLab,

I want change GaugeColor property when user clicks a button. My code looks like this:

```
@IBAction func didSelect(sender: UIButton) {
  self.gaugeView.gaugeColor = UIColor.brownColor()
}
```

But the color won't change. Any suggestions?

**Comment by lisardo** [comment]
I was able to hack a solution by using `setNeedsDisplay()` and changing `percentage`

```
self.gaugeView.gaugeColor = color
self.gaugeView.setNeedsDisplay()
self.gaugeView.percentage += 0.01
```

But I don't think this the best way to solve it.

**Comment by GnuRant** [comment]
Hi lisardo,
thanks for the report.
I will check the code as soon as possibile in order to fix the issue.
